# Crypto configuration for AmarVote Hyperledger Fabric Network

OrdererOrgs:
  - Name: Orderer
    Domain: amarvote.com
    EnableNodeOUs: true
    Specs:
      - Hostname: orderer

PeerOrgs:
  - Name: Org1
    Domain: org1.amarvote.com
    EnableNodeOUs: true
    Template:
      Count: 2
    Users:
      Count: 1
