import { StyleSheet } from '@react-pdf/renderer';
import { tokens } from '../../utils/certifiedLedger/tokens';

const PAGE_PAD = 54;

export const styles = StyleSheet.create({
  ivoryPage: {
    backgroundColor: tokens.ivory,
    color: tokens.ink,
    paddingTop: PAGE_PAD,
    paddingBottom: 64,
    paddingHorizontal: PAGE_PAD,
    fontFamily: 'Inter',
    fontSize: 10,
  },
  indigoPage: {
    backgroundColor: tokens.indigo,
    color: tokens.ivory,
    paddingTop: PAGE_PAD,
    paddingBottom: 64,
    paddingHorizontal: PAGE_PAD,
    fontFamily: 'Inter',
    fontSize: 10,
  },
  insetBorder: {
    position: 'absolute',
    top: 36,
    left: 36,
    right: 36,
    bottom: 36,
    borderWidth: 1,
    borderColor: tokens.hairlineOnIndigo,
  },
  wordmarkRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'flex-start',
  },
  wordmark: {
    fontFamily: 'Inter',
    fontSize: 9,
    letterSpacing: 3,
    fontWeight: 600,
  },
  wordmarkAmar: { color: tokens.ivory },
  wordmarkVote: { color: tokens.violetSoft },
  coverCaption: {
    fontFamily: 'JetBrains Mono',
    fontSize: 7,
    color: tokens.duskOnDark,
    textAlign: 'right',
    lineHeight: 1.45,
  },
  coverCenter: {
    flexGrow: 1,
    justifyContent: 'center',
    paddingVertical: 40,
  },
  coverKicker: {
    fontFamily: 'Inter',
    fontSize: 8,
    letterSpacing: 3.2,
    color: tokens.gold,
    fontWeight: 600,
    marginBottom: 14,
    textTransform: 'uppercase',
  },
  coverTitle: {
    fontFamily: 'Fraunces',
    fontSize: 42,
    fontWeight: 500,
    color: tokens.ivory,
    lineHeight: 1.08,
    maxWidth: '75%',
  },
  coverSubtitle: {
    marginTop: 28,
    fontFamily: 'Inter',
    fontSize: 10,
    color: tokens.duskOnDark,
    lineHeight: 1.55,
    maxWidth: '55%',
  },
  coverBottom: {
    position: 'absolute',
    left: PAGE_PAD,
    right: PAGE_PAD,
    bottom: 48,
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
  },
  coverMeta: {
    fontFamily: 'JetBrains Mono',
    fontSize: 7,
    color: tokens.duskOnDark,
  },
  certifiedRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
  },
  tealDot: {
    width: 6,
    height: 6,
    borderRadius: 3,
    backgroundColor: tokens.teal,
  },
  certifiedLabel: {
    fontFamily: 'Inter',
    fontSize: 8,
    letterSpacing: 2,
    color: tokens.teal,
    fontWeight: 600,
  },
  eyebrow: {
    fontFamily: 'Inter',
    fontSize: 8,
    letterSpacing: 2.4,
    color: tokens.duskOnLight,
    fontWeight: 600,
    textTransform: 'uppercase',
    marginBottom: 8,
  },
  pageTitle: {
    fontFamily: 'Fraunces',
    fontSize: 28,
    fontWeight: 500,
    color: tokens.ink,
    marginBottom: 8,
  },
  subtitle: {
    fontFamily: 'Inter',
    fontSize: 10,
    color: tokens.duskOnLight,
    marginBottom: 24,
    lineHeight: 1.5,
    maxWidth: '85%',
  },
  footerLeft: {
    position: 'absolute',
    left: PAGE_PAD,
    bottom: 28,
    fontFamily: 'JetBrains Mono',
    fontSize: 7,
    color: tokens.duskOnLight,
  },
  footerRight: {
    position: 'absolute',
    right: PAGE_PAD,
    bottom: 28,
    fontFamily: 'JetBrains Mono',
    fontSize: 7,
    color: tokens.duskOnLight,
  },
  footerIndigo: {
    color: tokens.duskOnDark,
  },
  heroWinnerBlock: {
    marginBottom: 22,
  },
  heroNameRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'flex-start',
    gap: 12,
  },
  heroName: {
    fontFamily: 'Fraunces',
    fontSize: 26,
    fontWeight: 500,
    color: tokens.ink,
    maxWidth: '65%',
    lineHeight: 1.15,
  },
  heroShare: {
    fontFamily: 'Fraunces',
    fontSize: 32,
    fontWeight: 500,
    color: tokens.violet,
  },
  goldRule: {
    marginTop: 8,
    marginBottom: 6,
    height: 1,
    backgroundColor: tokens.gold,
    width: '100%',
  },
  heroVotes: {
    fontFamily: 'JetBrains Mono',
    fontSize: 8,
    color: tokens.duskOnLight,
  },
  compactRow: {
    flexDirection: 'row',
    alignItems: 'center',
    borderBottomWidth: 1,
    borderBottomColor: tokens.hairlineOnIvory,
    paddingVertical: 7,
    gap: 8,
  },
  compactRank: {
    width: 42,
    fontFamily: 'Inter',
    fontWeight: 600,
    color: tokens.duskOnLight,
  },
  compactName: {
    flex: 1,
    fontFamily: 'Inter',
    fontWeight: 500,
    color: tokens.ink,
  },
  compactShare: {
    width: 48,
    textAlign: 'right',
    fontFamily: 'Fraunces',
    fontWeight: 500,
    color: tokens.violet,
  },
  compactVotes: {
    width: 72,
    textAlign: 'right',
    fontFamily: 'JetBrains Mono',
    color: tokens.duskOnLight,
  },
  tieBadge: {
    fontFamily: 'Inter',
    fontSize: 7,
    letterSpacing: 1.2,
    color: tokens.violet,
    fontWeight: 600,
    marginTop: 2,
  },
  fieldGrid: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    marginBottom: 18,
  },
  fieldCell: {
    width: '50%',
    paddingRight: 12,
    marginBottom: 14,
  },
  fieldLabel: {
    fontFamily: 'Inter',
    fontSize: 7,
    fontWeight: 600,
    letterSpacing: 1.8,
    color: tokens.duskOnLight,
    textTransform: 'uppercase',
    marginBottom: 4,
  },
  fieldValue: {
    fontFamily: 'Fraunces',
    fontSize: 13,
    fontWeight: 500,
    color: tokens.ink,
    lineHeight: 1.3,
  },
  totalsStrip: {
    flexDirection: 'row',
    borderTopWidth: 1,
    borderTopColor: tokens.hairlineOnIvory,
    paddingTop: 14,
    marginBottom: 20,
    gap: 36,
  },
  totalsLabel: {
    fontFamily: 'Inter',
    fontSize: 7,
    fontWeight: 600,
    letterSpacing: 1.6,
    color: tokens.duskOnLight,
    textTransform: 'uppercase',
    marginBottom: 4,
  },
  totalsNum: {
    fontFamily: 'Fraunces',
    fontSize: 20,
    fontWeight: 500,
    color: tokens.ink,
  },
  guardiansHeading: {
    fontFamily: 'Fraunces',
    fontSize: 14,
    fontWeight: 500,
    color: tokens.ink,
    marginBottom: 10,
  },
  guardianCols: {
    flexDirection: 'row',
    justifyContent: 'space-between',
  },
  guardianCol: {
    width: '48%',
  },
  guardianRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    borderBottomWidth: 1,
    borderBottomColor: tokens.hairlineOnIvory,
    paddingVertical: 5,
  },
  guardianSeq: {
    fontFamily: 'JetBrains Mono',
    fontSize: 8,
    color: tokens.duskOnLight,
    width: 28,
  },
  guardianEmail: {
    flex: 1,
    fontFamily: 'JetBrains Mono',
    fontSize: 8,
    color: tokens.ink,
  },
  chartFrame: {
    marginTop: 8,
    alignItems: 'center',
  },
  legendRow: {
    flexDirection: 'row',
    marginTop: 18,
    gap: 24,
  },
  legendCol: {
    flex: 1,
  },
  legendItem: {
    flexDirection: 'row',
    alignItems: 'center',
    marginBottom: 6,
    gap: 8,
  },
  legendSwatch: {
    width: 8,
    height: 8,
    borderRadius: 1,
  },
  legendName: {
    flex: 1,
    fontFamily: 'Inter',
    fontSize: 8,
    color: tokens.ink,
  },
  legendPct: {
    fontFamily: 'JetBrains Mono',
    fontSize: 8,
    color: tokens.duskOnLight,
  },
  continuedHeader: {
    fontFamily: 'Inter',
    fontSize: 8,
    color: tokens.duskOnLight,
    marginBottom: 10,
  },
  standingBlock: {
    flexDirection: 'row',
    marginBottom: 18,
    paddingBottom: 14,
    borderBottomWidth: 1,
    borderBottomColor: tokens.hairlineOnIvory,
  },
  standingRankCol: {
    width: 52,
    marginRight: 14,
  },
  standingRank: {
    fontFamily: 'Fraunces',
    fontSize: 28,
    fontStyle: 'italic',
    fontWeight: 400,
    color: tokens.violet,
    lineHeight: 1,
  },
  standingBody: {
    flex: 1,
  },
  standingNameRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'flex-start',
    gap: 10,
    marginBottom: 4,
  },
  standingName: {
    flex: 1,
    fontFamily: 'Fraunces',
    fontSize: 16,
    fontWeight: 500,
    color: tokens.ink,
    lineHeight: 1.2,
  },
  standingShare: {
    fontFamily: 'JetBrains Mono',
    fontSize: 9,
    color: tokens.duskOnLight,
  },
  standingParty: {
    fontFamily: 'Inter',
    fontSize: 8,
    letterSpacing: 1.4,
    color: tokens.violet,
    fontWeight: 600,
    textTransform: 'uppercase',
    marginBottom: 6,
  },
  standingQuote: {
    fontFamily: 'Fraunces',
    fontSize: 10,
    fontStyle: 'italic',
    color: tokens.ink,
    marginBottom: 10,
    maxWidth: '92%',
    lineHeight: 1.45,
  },
  policyLabel: {
    fontFamily: 'Inter',
    fontSize: 7,
    fontWeight: 600,
    letterSpacing: 1.6,
    color: tokens.duskOnLight,
    textTransform: 'uppercase',
    marginBottom: 3,
  },
  policyText: {
    fontFamily: 'Inter',
    fontSize: 9,
    color: tokens.ink,
    marginBottom: 8,
    lineHeight: 1.45,
  },
  standingSlogan: {
    fontFamily: 'Inter',
    fontSize: 9,
    fontWeight: 500,
    color: tokens.duskOnLight,
    marginTop: 2,
  },
  winnerBadge: {
    marginTop: 8,
    alignSelf: 'flex-start',
    borderWidth: 1,
    borderColor: tokens.gold,
    borderRadius: 2,
    paddingHorizontal: 8,
    paddingVertical: 3,
  },
  winnerBadgeText: {
    fontFamily: 'Inter',
    fontSize: 7,
    letterSpacing: 1.4,
    color: tokens.ink,
    fontWeight: 600,
  },
  colophonCenter: {
    flexGrow: 1,
    justifyContent: 'center',
    alignItems: 'center',
  },
  tealRing: {
    width: 48,
    height: 48,
    borderRadius: 24,
    borderWidth: 1.5,
    borderColor: tokens.teal,
    alignItems: 'center',
    justifyContent: 'center',
    marginBottom: 18,
  },
  colophonCertLabel: {
    fontFamily: 'Inter',
    fontSize: 9,
    letterSpacing: 2.4,
    color: tokens.teal,
    fontWeight: 600,
    marginBottom: 16,
  },
  colophonBody: {
    fontFamily: 'Fraunces',
    fontSize: 14,
    color: tokens.ivory,
    textAlign: 'center',
    lineHeight: 1.45,
    maxWidth: '78%',
    marginBottom: 14,
  },
  colophonFacts: {
    fontFamily: 'Inter',
    fontSize: 9,
    color: tokens.duskOnDark,
    textAlign: 'center',
    lineHeight: 1.5,
    maxWidth: '70%',
    marginBottom: 20,
  },
  colophonRule: {
    width: 80,
    height: 1,
    backgroundColor: tokens.hairlineOnIndigo,
    marginBottom: 16,
  },
  colophonStamp: {
    fontFamily: 'JetBrains Mono',
    fontSize: 7,
    color: tokens.duskOnDark,
    textAlign: 'center',
  },
});
