--
-- PostgreSQL database dump
--

\restrict 8BOMIzUmXyf4Romge46SdxkjWjRtZpeq4QPWXpXG1rHyQ3nrbLYnx79WOgx3ES4

-- Dumped from database version 17.7 (bdc8956)
-- Dumped by pg_dump version 17.7 (Ubuntu 17.7-3.pgdg24.04+1)

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET transaction_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

--
-- Name: pgcrypto; Type: EXTENSION; Schema: -; Owner: -
--

CREATE EXTENSION IF NOT EXISTS pgcrypto WITH SCHEMA public;


--
-- Name: EXTENSION pgcrypto; Type: COMMENT; Schema: -; Owner: 
--

COMMENT ON EXTENSION pgcrypto IS 'cryptographic functions';


--
-- Name: uuid-ossp; Type: EXTENSION; Schema: -; Owner: -
--

CREATE EXTENSION IF NOT EXISTS "uuid-ossp" WITH SCHEMA public;


--
-- Name: EXTENSION "uuid-ossp"; Type: COMMENT; Schema: -; Owner: 
--

COMMENT ON EXTENSION "uuid-ossp" IS 'generate universally unique identifiers (UUIDs)';


SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- Name: allowed_voters; Type: TABLE; Schema: public; Owner: neondb_owner
--

CREATE TABLE public.allowed_voters (
    election_id bigint NOT NULL,
    user_id integer NOT NULL,
    has_voted boolean DEFAULT false NOT NULL,
    id bigint NOT NULL
);


ALTER TABLE public.allowed_voters OWNER TO neondb_owner;

--
-- Name: allowed_voters_id_seq; Type: SEQUENCE; Schema: public; Owner: neondb_owner
--

ALTER TABLE public.allowed_voters ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.allowed_voters_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: audit_log; Type: TABLE; Schema: public; Owner: neondb_owner
--

CREATE TABLE public.audit_log (
    log_id integer NOT NULL,
    election_id integer,
    user_id integer,
    action_type text NOT NULL,
    action_details jsonb NOT NULL,
    "timestamp" timestamp with time zone DEFAULT CURRENT_TIMESTAMP,
    ip_address inet
);


ALTER TABLE public.audit_log OWNER TO neondb_owner;

--
-- Name: audit_log_log_id_seq; Type: SEQUENCE; Schema: public; Owner: neondb_owner
--

CREATE SEQUENCE public.audit_log_log_id_seq
    AS integer
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER SEQUENCE public.audit_log_log_id_seq OWNER TO neondb_owner;

--
-- Name: audit_log_log_id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: neondb_owner
--

ALTER SEQUENCE public.audit_log_log_id_seq OWNED BY public.audit_log.log_id;


--
-- Name: ballots; Type: TABLE; Schema: public; Owner: neondb_owner
--

CREATE TABLE public.ballots (
    ballot_id bigint NOT NULL,
    election_id bigint NOT NULL,
    submission_time timestamp with time zone DEFAULT CURRENT_TIMESTAMP,
    status text NOT NULL,
    cipher_text text NOT NULL,
    hash_code text NOT NULL,
    tracking_code text NOT NULL,
    master_nonce text,
    proof text,
    ballot_style text,
    ballot_nonces jsonb,
    contest_hashes jsonb,
    CONSTRAINT valid_ballot_status CHECK ((status = ANY (ARRAY['cast'::text, 'spoiled'::text, 'challenged'::text])))
);


ALTER TABLE public.ballots OWNER TO neondb_owner;

--
-- Name: ballots_ballot_id_seq; Type: SEQUENCE; Schema: public; Owner: neondb_owner
--

CREATE SEQUENCE public.ballots_ballot_id_seq
    AS integer
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER SEQUENCE public.ballots_ballot_id_seq OWNER TO neondb_owner;

--
-- Name: ballots_ballot_id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: neondb_owner
--

ALTER SEQUENCE public.ballots_ballot_id_seq OWNED BY public.ballots.ballot_id;


--
-- Name: blockchain_records; Type: TABLE; Schema: public; Owner: neondb_owner
--

CREATE TABLE public.blockchain_records (
    record_id bigint NOT NULL,
    ballot_hash character varying(255) NOT NULL,
    block_number character varying(255),
    blockchain_timestamp timestamp(6) with time zone,
    created_at timestamp(6) with time zone,
    election_id bigint NOT NULL,
    error_message text,
    last_retry_at timestamp(6) with time zone,
    retry_count integer,
    tracking_code character varying(255) NOT NULL,
    transaction_id text,
    updated_at timestamp(6) with time zone,
    verification_status character varying(255) NOT NULL
);


ALTER TABLE public.blockchain_records OWNER TO neondb_owner;

--
-- Name: blockchain_records_record_id_seq; Type: SEQUENCE; Schema: public; Owner: neondb_owner
--

ALTER TABLE public.blockchain_records ALTER COLUMN record_id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.blockchain_records_record_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: blockchain_transactions; Type: TABLE; Schema: public; Owner: neondb_owner
--

CREATE TABLE public.blockchain_transactions (
    id bigint NOT NULL,
    ballot_hash character varying(500),
    blockchain_tx_id character varying(200),
    confirmed_at timestamp(6) with time zone,
    created_at timestamp(6) with time zone NOT NULL,
    election_id bigint NOT NULL,
    error_message text,
    metadata text,
    previous_ballot_hash character varying(500),
    retry_count integer,
    sequence_number bigint,
    status character varying(20),
    tracking_code character varying(100),
    transaction_type character varying(50) NOT NULL,
    voter_id_hash character varying(500),
    CONSTRAINT blockchain_transactions_status_check CHECK (((status)::text = ANY ((ARRAY['PENDING'::character varying, 'CONFIRMED'::character varying, 'FAILED'::character varying, 'RETRYING'::character varying])::text[]))),
    CONSTRAINT blockchain_transactions_transaction_type_check CHECK (((transaction_type)::text = ANY ((ARRAY['ELECTION_INITIALIZED'::character varying, 'ELECTION_ACTIVATED'::character varying, 'BALLOT_CAST'::character varying, 'BALLOT_SPOILED'::character varying, 'ELECTION_CLOSED'::character varying, 'TALLY_PUBLISHED'::character varying, 'RESULTS_DECRYPTED'::character varying])::text[])))
);


ALTER TABLE public.blockchain_transactions OWNER TO neondb_owner;

--
-- Name: blockchain_transactions_id_seq; Type: SEQUENCE; Schema: public; Owner: neondb_owner
--

ALTER TABLE public.blockchain_transactions ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.blockchain_transactions_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: blocked_connections; Type: TABLE; Schema: public; Owner: neondb_owner
--

CREATE TABLE public.blocked_connections (
    blocked_connection_id integer NOT NULL,
    ip_address inet NOT NULL,
    device_id text,
    reason text NOT NULL,
    threat_level text NOT NULL,
    is_banned boolean DEFAULT true NOT NULL,
    created_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP,
    updated_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP,
    expires_at timestamp with time zone,
    note text,
    reported_by text,
    CONSTRAINT valid_threat_level CHECK ((threat_level = ANY (ARRAY['low'::text, 'medium'::text, 'high'::text, 'critical'::text])))
);


ALTER TABLE public.blocked_connections OWNER TO neondb_owner;

--
-- Name: blocked_connections_blocked_connection_id_seq; Type: SEQUENCE; Schema: public; Owner: neondb_owner
--

CREATE SEQUENCE public.blocked_connections_blocked_connection_id_seq
    AS integer
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER SEQUENCE public.blocked_connections_blocked_connection_id_seq OWNER TO neondb_owner;

--
-- Name: blocked_connections_blocked_connection_id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: neondb_owner
--

ALTER SEQUENCE public.blocked_connections_blocked_connection_id_seq OWNED BY public.blocked_connections.blocked_connection_id;


--
-- Name: challenges; Type: TABLE; Schema: public; Owner: neondb_owner
--

CREATE TABLE public.challenges (
    challenge_id integer NOT NULL,
    election_id integer NOT NULL,
    guardian_id integer NOT NULL,
    challenge_data text NOT NULL,
    response_data text,
    status text DEFAULT 'pending'::text NOT NULL,
    created_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT valid_challenge_status CHECK ((status = ANY (ARRAY['pending'::text, 'resolved'::text, 'failed'::text])))
);


ALTER TABLE public.challenges OWNER TO neondb_owner;

--
-- Name: challenges_challenge_id_seq; Type: SEQUENCE; Schema: public; Owner: neondb_owner
--

CREATE SEQUENCE public.challenges_challenge_id_seq
    AS integer
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER SEQUENCE public.challenges_challenge_id_seq OWNER TO neondb_owner;

--
-- Name: challenges_challenge_id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: neondb_owner
--

ALTER SEQUENCE public.challenges_challenge_id_seq OWNED BY public.challenges.challenge_id;


--
-- Name: compensated_decryptions; Type: TABLE; Schema: public; Owner: neondb_owner
--

CREATE TABLE public.compensated_decryptions (
    compensating_guardian_sequence integer NOT NULL,
    election_id bigint NOT NULL,
    missing_guardian_sequence integer NOT NULL,
    compensated_ballot_share text NOT NULL,
    compensated_tally_share text NOT NULL
);


ALTER TABLE public.compensated_decryptions OWNER TO neondb_owner;

--
-- Name: decryptions; Type: TABLE; Schema: public; Owner: neondb_owner
--

CREATE TABLE public.decryptions (
    decryption_id integer NOT NULL,
    election_id integer NOT NULL,
    guardian_id integer NOT NULL,
    decryption_proof text NOT NULL,
    decrypted_tally text,
    lagrange_coefficient text,
    date_performed timestamp with time zone DEFAULT CURRENT_TIMESTAMP
);


ALTER TABLE public.decryptions OWNER TO neondb_owner;

--
-- Name: decryptions_decryption_id_seq; Type: SEQUENCE; Schema: public; Owner: neondb_owner
--

CREATE SEQUENCE public.decryptions_decryption_id_seq
    AS integer
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER SEQUENCE public.decryptions_decryption_id_seq OWNER TO neondb_owner;

--
-- Name: decryptions_decryption_id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: neondb_owner
--

ALTER SEQUENCE public.decryptions_decryption_id_seq OWNED BY public.decryptions.decryption_id;


--
-- Name: election_choices; Type: TABLE; Schema: public; Owner: neondb_owner
--

CREATE TABLE public.election_choices (
    choice_id bigint NOT NULL,
    election_id bigint NOT NULL,
    option_title text NOT NULL,
    option_description text,
    party_name text,
    candidate_pic text,
    party_pic text,
    total_votes integer DEFAULT 0 NOT NULL
);


ALTER TABLE public.election_choices OWNER TO neondb_owner;

--
-- Name: election_choices_choice_id_seq; Type: SEQUENCE; Schema: public; Owner: neondb_owner
--

CREATE SEQUENCE public.election_choices_choice_id_seq
    AS integer
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER SEQUENCE public.election_choices_choice_id_seq OWNER TO neondb_owner;

--
-- Name: election_choices_choice_id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: neondb_owner
--

ALTER SEQUENCE public.election_choices_choice_id_seq OWNED BY public.election_choices.choice_id;


--
-- Name: elections; Type: TABLE; Schema: public; Owner: neondb_owner
--

CREATE TABLE public.elections (
    election_id bigint NOT NULL,
    election_title character varying(255) NOT NULL,
    election_description text,
    number_of_guardians integer NOT NULL,
    election_quorum integer NOT NULL,
    no_of_candidates integer NOT NULL,
    joint_public_key text,
    manifest_hash text,
    status text DEFAULT 'draft'::text NOT NULL,
    starting_time timestamp with time zone NOT NULL,
    ending_time timestamp with time zone NOT NULL,
    encrypted_tally text,
    base_hash text,
    created_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP,
    profile_pic text,
    admin_email text,
    privacy text,
    eligibility text,
    CONSTRAINT elections_election_quorum_check CHECK ((election_quorum > 0)),
    CONSTRAINT elections_no_of_candidates_check CHECK ((no_of_candidates > 0)),
    CONSTRAINT elections_number_of_guardians_check CHECK ((number_of_guardians > 0)),
    CONSTRAINT valid_election_times CHECK ((ending_time > starting_time)),
    CONSTRAINT valid_status CHECK ((status = ANY (ARRAY['draft'::text, 'active'::text, 'completed'::text, 'decrypted'::text])))
);


ALTER TABLE public.elections OWNER TO neondb_owner;

--
-- Name: elections_election_id_seq; Type: SEQUENCE; Schema: public; Owner: neondb_owner
--

CREATE SEQUENCE public.elections_election_id_seq
    AS integer
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER SEQUENCE public.elections_election_id_seq OWNER TO neondb_owner;

--
-- Name: elections_election_id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: neondb_owner
--

ALTER SEQUENCE public.elections_election_id_seq OWNED BY public.elections.election_id;


--
-- Name: guardians; Type: TABLE; Schema: public; Owner: neondb_owner
--

CREATE TABLE public.guardians (
    election_id bigint NOT NULL,
    user_id integer NOT NULL,
    guardian_public_key text NOT NULL,
    sequence_order integer NOT NULL,
    decrypted_or_not boolean DEFAULT false NOT NULL,
    partial_decrypted_tally text,
    proof text,
    id bigint NOT NULL,
    guardian_decryption_key text,
    tally_share text,
    ballot_share text,
    key_backup text,
    credentials text,
    CONSTRAINT guardians_sequence_order_check CHECK ((sequence_order > 0))
);


ALTER TABLE public.guardians OWNER TO neondb_owner;

--
-- Name: guardians_id_seq; Type: SEQUENCE; Schema: public; Owner: neondb_owner
--

ALTER TABLE public.guardians ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.guardians_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: password_reset_tokens; Type: TABLE; Schema: public; Owner: neondb_owner
--

CREATE TABLE public.password_reset_tokens (
    token_id uuid DEFAULT public.uuid_generate_v4() NOT NULL,
    email character varying(255) NOT NULL,
    token character varying(255) NOT NULL,
    used boolean DEFAULT false NOT NULL,
    expiry_time timestamp with time zone NOT NULL,
    created_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP,
    used_at timestamp with time zone
);


ALTER TABLE public.password_reset_tokens OWNER TO neondb_owner;

--
-- Name: signup_verification; Type: TABLE; Schema: public; Owner: neondb_owner
--

CREATE TABLE public.signup_verification (
    id bigint NOT NULL,
    verification_code character varying(255) NOT NULL,
    email character varying(255) NOT NULL,
    expiry_date timestamp with time zone NOT NULL
);


ALTER TABLE public.signup_verification OWNER TO neondb_owner;

--
-- Name: signup_verification_id_seq; Type: SEQUENCE; Schema: public; Owner: neondb_owner
--

CREATE SEQUENCE public.signup_verification_id_seq
    AS integer
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER SEQUENCE public.signup_verification_id_seq OWNER TO neondb_owner;

--
-- Name: signup_verification_id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: neondb_owner
--

ALTER SEQUENCE public.signup_verification_id_seq OWNED BY public.signup_verification.id;


--
-- Name: submitted_ballots; Type: TABLE; Schema: public; Owner: neondb_owner
--

CREATE TABLE public.submitted_ballots (
    id integer NOT NULL,
    election_id bigint NOT NULL,
    submission_time timestamp with time zone DEFAULT CURRENT_TIMESTAMP,
    cipher_text text NOT NULL,
    submitted_ballot_id bigint NOT NULL,
    created_at timestamp(6) with time zone
);


ALTER TABLE public.submitted_ballots OWNER TO neondb_owner;

--
-- Name: submitted_ballots_id_seq; Type: SEQUENCE; Schema: public; Owner: neondb_owner
--

CREATE SEQUENCE public.submitted_ballots_id_seq
    AS integer
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER SEQUENCE public.submitted_ballots_id_seq OWNER TO neondb_owner;

--
-- Name: submitted_ballots_id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: neondb_owner
--

ALTER SEQUENCE public.submitted_ballots_id_seq OWNED BY public.submitted_ballots.id;


--
-- Name: submitted_ballots_submitted_ballot_id_seq; Type: SEQUENCE; Schema: public; Owner: neondb_owner
--

ALTER TABLE public.submitted_ballots ALTER COLUMN submitted_ballot_id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.submitted_ballots_submitted_ballot_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: users; Type: TABLE; Schema: public; Owner: neondb_owner
--

CREATE TABLE public.users (
    user_id integer NOT NULL,
    user_email character varying(255) NOT NULL,
    is_verified boolean DEFAULT false NOT NULL,
    user_name character varying(255) NOT NULL,
    password_hash character varying(255) NOT NULL,
    created_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP,
    last_login timestamp with time zone,
    profile_pic character varying(255),
    nid character varying(255)
);


ALTER TABLE public.users OWNER TO neondb_owner;

--
-- Name: users_user_id_seq; Type: SEQUENCE; Schema: public; Owner: neondb_owner
--

CREATE SEQUENCE public.users_user_id_seq
    AS integer
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER SEQUENCE public.users_user_id_seq OWNER TO neondb_owner;

--
-- Name: users_user_id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: neondb_owner
--

ALTER SEQUENCE public.users_user_id_seq OWNED BY public.users.user_id;


--
-- Name: audit_log log_id; Type: DEFAULT; Schema: public; Owner: neondb_owner
--

ALTER TABLE ONLY public.audit_log ALTER COLUMN log_id SET DEFAULT nextval('public.audit_log_log_id_seq'::regclass);


--
-- Name: ballots ballot_id; Type: DEFAULT; Schema: public; Owner: neondb_owner
--

ALTER TABLE ONLY public.ballots ALTER COLUMN ballot_id SET DEFAULT nextval('public.ballots_ballot_id_seq'::regclass);


--
-- Name: blocked_connections blocked_connection_id; Type: DEFAULT; Schema: public; Owner: neondb_owner
--

ALTER TABLE ONLY public.blocked_connections ALTER COLUMN blocked_connection_id SET DEFAULT nextval('public.blocked_connections_blocked_connection_id_seq'::regclass);


--
-- Name: challenges challenge_id; Type: DEFAULT; Schema: public; Owner: neondb_owner
--

ALTER TABLE ONLY public.challenges ALTER COLUMN challenge_id SET DEFAULT nextval('public.challenges_challenge_id_seq'::regclass);


--
-- Name: decryptions decryption_id; Type: DEFAULT; Schema: public; Owner: neondb_owner
--

ALTER TABLE ONLY public.decryptions ALTER COLUMN decryption_id SET DEFAULT nextval('public.decryptions_decryption_id_seq'::regclass);


--
-- Name: election_choices choice_id; Type: DEFAULT; Schema: public; Owner: neondb_owner
--

ALTER TABLE ONLY public.election_choices ALTER COLUMN choice_id SET DEFAULT nextval('public.election_choices_choice_id_seq'::regclass);


--
-- Name: elections election_id; Type: DEFAULT; Schema: public; Owner: neondb_owner
--

ALTER TABLE ONLY public.elections ALTER COLUMN election_id SET DEFAULT nextval('public.elections_election_id_seq'::regclass);


--
-- Name: signup_verification id; Type: DEFAULT; Schema: public; Owner: neondb_owner
--

ALTER TABLE ONLY public.signup_verification ALTER COLUMN id SET DEFAULT nextval('public.signup_verification_id_seq'::regclass);


--
-- Name: submitted_ballots id; Type: DEFAULT; Schema: public; Owner: neondb_owner
--

ALTER TABLE ONLY public.submitted_ballots ALTER COLUMN id SET DEFAULT nextval('public.submitted_ballots_id_seq'::regclass);


--
-- Name: users user_id; Type: DEFAULT; Schema: public; Owner: neondb_owner
--

ALTER TABLE ONLY public.users ALTER COLUMN user_id SET DEFAULT nextval('public.users_user_id_seq'::regclass);


--
-- Name: allowed_voters allowed_voters_pkey; Type: CONSTRAINT; Schema: public; Owner: neondb_owner
--

ALTER TABLE ONLY public.allowed_voters
    ADD CONSTRAINT allowed_voters_pkey PRIMARY KEY (election_id, user_id);


--
-- Name: audit_log audit_log_pkey; Type: CONSTRAINT; Schema: public; Owner: neondb_owner
--

ALTER TABLE ONLY public.audit_log
    ADD CONSTRAINT audit_log_pkey PRIMARY KEY (log_id);


--
-- Name: ballots ballots_pkey; Type: CONSTRAINT; Schema: public; Owner: neondb_owner
--

ALTER TABLE ONLY public.ballots
    ADD CONSTRAINT ballots_pkey PRIMARY KEY (ballot_id);


--
-- Name: blockchain_records blockchain_records_pkey; Type: CONSTRAINT; Schema: public; Owner: neondb_owner
--

ALTER TABLE ONLY public.blockchain_records
    ADD CONSTRAINT blockchain_records_pkey PRIMARY KEY (record_id);


--
-- Name: blockchain_transactions blockchain_transactions_pkey; Type: CONSTRAINT; Schema: public; Owner: neondb_owner
--

ALTER TABLE ONLY public.blockchain_transactions
    ADD CONSTRAINT blockchain_transactions_pkey PRIMARY KEY (id);


--
-- Name: blocked_connections blocked_connections_pkey; Type: CONSTRAINT; Schema: public; Owner: neondb_owner
--

ALTER TABLE ONLY public.blocked_connections
    ADD CONSTRAINT blocked_connections_pkey PRIMARY KEY (blocked_connection_id);


--
-- Name: challenges challenges_pkey; Type: CONSTRAINT; Schema: public; Owner: neondb_owner
--

ALTER TABLE ONLY public.challenges
    ADD CONSTRAINT challenges_pkey PRIMARY KEY (challenge_id);


--
-- Name: compensated_decryptions compensated_decryptions_pkey; Type: CONSTRAINT; Schema: public; Owner: neondb_owner
--

ALTER TABLE ONLY public.compensated_decryptions
    ADD CONSTRAINT compensated_decryptions_pkey PRIMARY KEY (compensating_guardian_sequence, election_id, missing_guardian_sequence);


--
-- Name: decryptions decryptions_pkey; Type: CONSTRAINT; Schema: public; Owner: neondb_owner
--

ALTER TABLE ONLY public.decryptions
    ADD CONSTRAINT decryptions_pkey PRIMARY KEY (decryption_id);


--
-- Name: election_choices election_choices_pkey; Type: CONSTRAINT; Schema: public; Owner: neondb_owner
--

ALTER TABLE ONLY public.election_choices
    ADD CONSTRAINT election_choices_pkey PRIMARY KEY (choice_id);


--
-- Name: elections elections_pkey; Type: CONSTRAINT; Schema: public; Owner: neondb_owner
--

ALTER TABLE ONLY public.elections
    ADD CONSTRAINT elections_pkey PRIMARY KEY (election_id);


--
-- Name: guardians guardians_pkey; Type: CONSTRAINT; Schema: public; Owner: neondb_owner
--

ALTER TABLE ONLY public.guardians
    ADD CONSTRAINT guardians_pkey PRIMARY KEY (election_id, user_id);


--
-- Name: password_reset_tokens password_reset_tokens_pkey; Type: CONSTRAINT; Schema: public; Owner: neondb_owner
--

ALTER TABLE ONLY public.password_reset_tokens
    ADD CONSTRAINT password_reset_tokens_pkey PRIMARY KEY (token_id);


--
-- Name: signup_verification signup_verification_pkey; Type: CONSTRAINT; Schema: public; Owner: neondb_owner
--

ALTER TABLE ONLY public.signup_verification
    ADD CONSTRAINT signup_verification_pkey PRIMARY KEY (id);


--
-- Name: signup_verification signup_verification_verification_code_key; Type: CONSTRAINT; Schema: public; Owner: neondb_owner
--

ALTER TABLE ONLY public.signup_verification
    ADD CONSTRAINT signup_verification_verification_code_key UNIQUE (verification_code);


--
-- Name: submitted_ballots submitted_ballots_pkey; Type: CONSTRAINT; Schema: public; Owner: neondb_owner
--

ALTER TABLE ONLY public.submitted_ballots
    ADD CONSTRAINT submitted_ballots_pkey PRIMARY KEY (id);


--
-- Name: blockchain_records ukdf9x0ufsto24erpbb6mbcdmpu; Type: CONSTRAINT; Schema: public; Owner: neondb_owner
--

ALTER TABLE ONLY public.blockchain_records
    ADD CONSTRAINT ukdf9x0ufsto24erpbb6mbcdmpu UNIQUE (tracking_code);


--
-- Name: election_choices unique_election_option; Type: CONSTRAINT; Schema: public; Owner: neondb_owner
--

ALTER TABLE ONLY public.election_choices
    ADD CONSTRAINT unique_election_option UNIQUE (election_id, option_title);


--
-- Name: blocked_connections unique_ip_device; Type: CONSTRAINT; Schema: public; Owner: neondb_owner
--

ALTER TABLE ONLY public.blocked_connections
    ADD CONSTRAINT unique_ip_device UNIQUE (ip_address, device_id);


--
-- Name: guardians unique_sequence_order; Type: CONSTRAINT; Schema: public; Owner: neondb_owner
--

ALTER TABLE ONLY public.guardians
    ADD CONSTRAINT unique_sequence_order UNIQUE (election_id, sequence_order);


--
-- Name: ballots unique_tracking_code; Type: CONSTRAINT; Schema: public; Owner: neondb_owner
--

ALTER TABLE ONLY public.ballots
    ADD CONSTRAINT unique_tracking_code UNIQUE (tracking_code);


--
-- Name: users users_pkey; Type: CONSTRAINT; Schema: public; Owner: neondb_owner
--

ALTER TABLE ONLY public.users
    ADD CONSTRAINT users_pkey PRIMARY KEY (user_id);


--
-- Name: users users_user_email_key; Type: CONSTRAINT; Schema: public; Owner: neondb_owner
--

ALTER TABLE ONLY public.users
    ADD CONSTRAINT users_user_email_key UNIQUE (user_email);


--
-- Name: idx_audit_log_election; Type: INDEX; Schema: public; Owner: neondb_owner
--

CREATE INDEX idx_audit_log_election ON public.audit_log USING btree (election_id);


--
-- Name: idx_audit_log_user; Type: INDEX; Schema: public; Owner: neondb_owner
--

CREATE INDEX idx_audit_log_user ON public.audit_log USING btree (user_id);


--
-- Name: idx_ballots_election; Type: INDEX; Schema: public; Owner: neondb_owner
--

CREATE INDEX idx_ballots_election ON public.ballots USING btree (election_id);


--
-- Name: idx_ballots_tracking; Type: INDEX; Schema: public; Owner: neondb_owner
--

CREATE INDEX idx_ballots_tracking ON public.ballots USING btree (tracking_code);


--
-- Name: idx_blockchain_tx_id; Type: INDEX; Schema: public; Owner: neondb_owner
--

CREATE INDEX idx_blockchain_tx_id ON public.blockchain_transactions USING btree (blockchain_tx_id);


--
-- Name: idx_blocked_ips; Type: INDEX; Schema: public; Owner: neondb_owner
--

CREATE INDEX idx_blocked_ips ON public.blocked_connections USING btree (ip_address);


--
-- Name: idx_choices_election; Type: INDEX; Schema: public; Owner: neondb_owner
--

CREATE INDEX idx_choices_election ON public.election_choices USING btree (election_id);


--
-- Name: idx_compensated_decryptions_pk; Type: INDEX; Schema: public; Owner: neondb_owner
--

CREATE INDEX idx_compensated_decryptions_pk ON public.compensated_decryptions USING btree (election_id, compensating_guardian_sequence, missing_guardian_sequence);


--
-- Name: idx_election_id; Type: INDEX; Schema: public; Owner: neondb_owner
--

CREATE INDEX idx_election_id ON public.blockchain_transactions USING btree (election_id);


--
-- Name: idx_guardians_election; Type: INDEX; Schema: public; Owner: neondb_owner
--

CREATE INDEX idx_guardians_election ON public.guardians USING btree (election_id);


--
-- Name: idx_password_reset_email; Type: INDEX; Schema: public; Owner: neondb_owner
--

CREATE INDEX idx_password_reset_email ON public.password_reset_tokens USING btree (email);


--
-- Name: idx_password_reset_token; Type: INDEX; Schema: public; Owner: neondb_owner
--

CREATE INDEX idx_password_reset_token ON public.password_reset_tokens USING btree (token);


--
-- Name: idx_submitted_ballots_election; Type: INDEX; Schema: public; Owner: neondb_owner
--

CREATE INDEX idx_submitted_ballots_election ON public.submitted_ballots USING btree (election_id);


--
-- Name: idx_tracking_code; Type: INDEX; Schema: public; Owner: neondb_owner
--

CREATE INDEX idx_tracking_code ON public.blockchain_transactions USING btree (tracking_code);


--
-- Name: idx_transaction_type; Type: INDEX; Schema: public; Owner: neondb_owner
--

CREATE INDEX idx_transaction_type ON public.blockchain_transactions USING btree (transaction_type);


--
-- Name: idx_verification_code; Type: INDEX; Schema: public; Owner: neondb_owner
--

CREATE INDEX idx_verification_code ON public.signup_verification USING btree (verification_code);


--
-- Name: idx_verification_code_email; Type: INDEX; Schema: public; Owner: neondb_owner
--

CREATE INDEX idx_verification_code_email ON public.signup_verification USING btree (email);


--
-- Name: idx_voters_election; Type: INDEX; Schema: public; Owner: neondb_owner
--

CREATE INDEX idx_voters_election ON public.allowed_voters USING btree (election_id);


--
-- Name: idx_voters_user; Type: INDEX; Schema: public; Owner: neondb_owner
--

CREATE INDEX idx_voters_user ON public.allowed_voters USING btree (user_id);


--
-- Name: unique_election_cipher_prefix; Type: INDEX; Schema: public; Owner: neondb_owner
--

CREATE UNIQUE INDEX unique_election_cipher_prefix ON public.submitted_ballots USING btree (election_id, "left"(cipher_text, 30));


--
-- Name: compensated_decryptions fk_compensating_guardian; Type: FK CONSTRAINT; Schema: public; Owner: neondb_owner
--

ALTER TABLE ONLY public.compensated_decryptions
    ADD CONSTRAINT fk_compensating_guardian FOREIGN KEY (election_id, compensating_guardian_sequence) REFERENCES public.guardians(election_id, sequence_order) ON DELETE CASCADE;


--
-- Name: allowed_voters fk_election; Type: FK CONSTRAINT; Schema: public; Owner: neondb_owner
--

ALTER TABLE ONLY public.allowed_voters
    ADD CONSTRAINT fk_election FOREIGN KEY (election_id) REFERENCES public.elections(election_id) ON DELETE CASCADE;


--
-- Name: audit_log fk_election; Type: FK CONSTRAINT; Schema: public; Owner: neondb_owner
--

ALTER TABLE ONLY public.audit_log
    ADD CONSTRAINT fk_election FOREIGN KEY (election_id) REFERENCES public.elections(election_id) ON DELETE SET NULL;


--
-- Name: ballots fk_election; Type: FK CONSTRAINT; Schema: public; Owner: neondb_owner
--

ALTER TABLE ONLY public.ballots
    ADD CONSTRAINT fk_election FOREIGN KEY (election_id) REFERENCES public.elections(election_id) ON DELETE CASCADE;


--
-- Name: compensated_decryptions fk_election; Type: FK CONSTRAINT; Schema: public; Owner: neondb_owner
--

ALTER TABLE ONLY public.compensated_decryptions
    ADD CONSTRAINT fk_election FOREIGN KEY (election_id) REFERENCES public.elections(election_id) ON DELETE CASCADE;


--
-- Name: election_choices fk_election; Type: FK CONSTRAINT; Schema: public; Owner: neondb_owner
--

ALTER TABLE ONLY public.election_choices
    ADD CONSTRAINT fk_election FOREIGN KEY (election_id) REFERENCES public.elections(election_id) ON DELETE CASCADE;


--
-- Name: guardians fk_election; Type: FK CONSTRAINT; Schema: public; Owner: neondb_owner
--

ALTER TABLE ONLY public.guardians
    ADD CONSTRAINT fk_election FOREIGN KEY (election_id) REFERENCES public.elections(election_id) ON DELETE CASCADE;


--
-- Name: submitted_ballots fk_election; Type: FK CONSTRAINT; Schema: public; Owner: neondb_owner
--

ALTER TABLE ONLY public.submitted_ballots
    ADD CONSTRAINT fk_election FOREIGN KEY (election_id) REFERENCES public.elections(election_id) ON DELETE CASCADE;


--
-- Name: challenges fk_guardian; Type: FK CONSTRAINT; Schema: public; Owner: neondb_owner
--

ALTER TABLE ONLY public.challenges
    ADD CONSTRAINT fk_guardian FOREIGN KEY (election_id, guardian_id) REFERENCES public.guardians(election_id, user_id);


--
-- Name: decryptions fk_guardian; Type: FK CONSTRAINT; Schema: public; Owner: neondb_owner
--

ALTER TABLE ONLY public.decryptions
    ADD CONSTRAINT fk_guardian FOREIGN KEY (election_id, guardian_id) REFERENCES public.guardians(election_id, user_id);


--
-- Name: compensated_decryptions fk_missing_guardian; Type: FK CONSTRAINT; Schema: public; Owner: neondb_owner
--

ALTER TABLE ONLY public.compensated_decryptions
    ADD CONSTRAINT fk_missing_guardian FOREIGN KEY (election_id, missing_guardian_sequence) REFERENCES public.guardians(election_id, sequence_order) ON DELETE CASCADE;


--
-- Name: allowed_voters fk_user; Type: FK CONSTRAINT; Schema: public; Owner: neondb_owner
--

ALTER TABLE ONLY public.allowed_voters
    ADD CONSTRAINT fk_user FOREIGN KEY (user_id) REFERENCES public.users(user_id) ON DELETE CASCADE;


--
-- Name: audit_log fk_user; Type: FK CONSTRAINT; Schema: public; Owner: neondb_owner
--

ALTER TABLE ONLY public.audit_log
    ADD CONSTRAINT fk_user FOREIGN KEY (user_id) REFERENCES public.users(user_id) ON DELETE SET NULL;


--
-- Name: guardians fk_user; Type: FK CONSTRAINT; Schema: public; Owner: neondb_owner
--

ALTER TABLE ONLY public.guardians
    ADD CONSTRAINT fk_user FOREIGN KEY (user_id) REFERENCES public.users(user_id) ON DELETE CASCADE;


--
-- Name: password_reset_tokens password_reset_tokens_email_fkey; Type: FK CONSTRAINT; Schema: public; Owner: neondb_owner
--

ALTER TABLE ONLY public.password_reset_tokens
    ADD CONSTRAINT password_reset_tokens_email_fkey FOREIGN KEY (email) REFERENCES public.users(user_email) ON DELETE CASCADE;


--
-- Name: DEFAULT PRIVILEGES FOR SEQUENCES; Type: DEFAULT ACL; Schema: public; Owner: cloud_admin
--

ALTER DEFAULT PRIVILEGES FOR ROLE cloud_admin IN SCHEMA public GRANT ALL ON SEQUENCES TO neon_superuser WITH GRANT OPTION;


--
-- Name: DEFAULT PRIVILEGES FOR TABLES; Type: DEFAULT ACL; Schema: public; Owner: cloud_admin
--

ALTER DEFAULT PRIVILEGES FOR ROLE cloud_admin IN SCHEMA public GRANT ALL ON TABLES TO neon_superuser WITH GRANT OPTION;


--
-- PostgreSQL database dump complete
--

\unrestrict 8BOMIzUmXyf4Romge46SdxkjWjRtZpeq4QPWXpXG1rHyQ3nrbLYnx79WOgx3ES4

