name: CI

on:
  push:
    paths:
      - 'docker-compose.yml'         # Add this line to cover all amarvote subfolders/files
      - 'Database/**'       # Include Database folder
      - 'Microservice/**'
      - 'docs/**'          # Include docs folder
      - 'backend/**'
      - 'frontend/**'
      - '.github/workflows/ci.yml'
      - '.github/workflows/docker-deploy.yml'
  pull_request:
    paths:
      - 'docker-compose.yml'         # Add this line to cover all amarvote subfolders/files
      - 'Database/**'       # Include Database folder
      - 'Microservice/**'
      - 'docs/**'          # Include docs folder
      - 'backend/**'
      - 'frontend/**'
      - '.github/workflows/ci.yml'
      - '.github/workflows/docker-deploy.yml'

jobs:
  backend:
    name: Backend (Spring Boot)
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./backend
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'

      - name: Cache Maven packages
        uses: actions/cache@v4
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-

      - name: Build with Maven (Skip Tests)
        run: mvn -B package -DskipTests

      - name: Run Unit Tests
        run: mvn -B test

  frontend:
    name: Frontend (React)
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./frontend
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install dependencies
        run: npm ci || npm install

      - name: Lint (optional)
        run: npm run lint || echo "No lint script found"

      - name: Test (optional)
        run: echo "Skipping frontend tests for now"
