name: Deploy to Azure VM

on:
  workflow_run:
    workflows: ["CI"]
    types:
      - completed

jobs:
  deploy:
    if: ${{ github.event.workflow_run.conclusion == 'success' && github.event.workflow_run.head_branch == 'main' }}
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Validate files
        run: |
          ls -la frontend/ backend/
          [ ! -f frontend/package.json ] && echo "❌ Missing package.json" && exit 1
          [ ! -f backend/pom.xml ] && echo "❌ Missing pom.xml" && exit 1

      - name: Verify VM Docker
        run: |
          ssh ${{ secrets.AZURE_VM_USERNAME }}@${{ secrets.AZURE_VM_HOST }} \
            "docker --version || (echo 'Docker not installed'; exit 1)"

      - name: Create app directory
        run: |
          ssh ${{ secrets.AZURE_VM_USERNAME }}@${{ secrets.AZURE_VM_HOST }} \
            "mkdir -p /home/${{ secrets.AZURE_VM_USERNAME }}/app"

      - name: Copy files
        run: |
          scp -r . ${{ secrets.AZURE_VM_USERNAME }}@${{ secrets.AZURE_VM_HOST }}:/home/${{ secrets.AZURE_VM_USERNAME }}/app

      - name: Deploy
        run: |
          docker context create azure-vm --docker "host=ssh://${{ secrets.AZURE_VM_USERNAME }}@${{ secrets.AZURE_VM_HOST }}"
          docker context use azure-vm
          docker compose -f docker-compose.yml up --build -d
          docker context use default

      - name: Verify
        run: |
          curl -sSf http://${{ secrets.AZURE_VM_HOST }} || exit 1