name: Continuous Deployment (CD)

on:
  push:
    branches: [main]  # Changed from 'deployment' to 'main'

jobs:
  deploy-to-vm:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up SSH
        uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: ${{ secrets.AZURE_VM_SECRET }}

      - name: Add VM to known hosts
        run: |
          mkdir -p ~/.ssh
          chmod 700 ~/.ssh
          ssh-keyscan -H ${{ secrets.AZURE_VM_HOST }} >> ~/.ssh/known_hosts
          chmod 600 ~/.ssh/known_hosts

      - name: Deploy to Azure VM
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.AZURE_VM_HOST }}
          username: amarvote
          key: ${{ secrets.AZURE_VM_SECRET }}
          script: |
            cd /home/amarvote/app  # Changed to consistent directory
            git pull origin main    # Changed from 'deployment' to 'main'
            docker compose down
            docker image prune -af
            docker compose pull
            docker compose up -d --build
            sleep 10  # Wait for containers to initialize
            docker ps -a
            curl -I http://localhost || true  # Verify frontend
          timeout: 60m