name: Secrets Check

on:
  workflow_dispatch:
  pull_request:
    branches: [ main ]
    paths:
      - 'backend/src/main/resources/application.properties'
      - 'backend/src/main/resources/application.yml'

jobs:
  check-secrets:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Check for hardcoded secrets
      run: |
        echo "Checking for hardcoded secrets in configuration files..."
        ! grep -i "password\|secret\|key\|token" --include="*.properties" --include="*.yml" -r backend/src/main/resources/ | grep -v "\\${"
      
    - name: Validate properties files
      run: |
        echo "Ensuring all sensitive values use environment variables..."
        grep -i "brevo.api.key\|spring.datasource.password\|jwt.secret" --include="*.properties" -r backend/src/main/resources/ | grep "\\${"
